#include "Commands/BlueprintGraph/ExtractionFootprintGraphBuilder.h"

#include "Commands/EpicUnrealMCPCommonUtils.h"
#include "Components/SkeletalMeshComponent.h"
#include "EdGraph/EdGraph.h"
#include "EdGraph/EdGraphNode.h"
#include "EdGraph/EdGraphPin.h"
#include "EdGraphSchema_K2.h"
#include "EditorAssetLibrary.h"
#include "Engine/Blueprint.h"
#include "GameFramework/Actor.h"
#include "K2Node_CallFunction.h"
#include "K2Node_DynamicCast.h"
#include "K2Node_Event.h"
#include "K2Node_FunctionEntry.h"
#include "K2Node_IfThenElse.h"
#include "K2Node_VariableGet.h"
#include "K2Node_VariableSet.h"
#include "Kismet/GameplayStatics.h"
#include "Kismet/KismetMathLibrary.h"
#include "Kismet/KismetSystemLibrary.h"
#include "Kismet2/BlueprintEditorUtils.h"
#include "Kismet2/KismetEditorUtilities.h"
#include "NiagaraFunctionLibrary.h"
#include "NiagaraSystem.h"
#include "UObject/UnrealType.h"

namespace
{
const FString GeneratedComment = TEXT("Generated by setup_extraction_footprint_graph");
const FName FnLeft = TEXT("MCP_CheckLeftFoot");
const FName FnRight = TEXT("MCP_CheckRightFoot");

struct FBuildStats
{
    int32 NodesCreated = 0;
    int32 NodesRemoved = 0;
    int32 VariablesAdded = 0;
    int32 VariablesUpdated = 0;
    TArray<FString> Warnings;
};

FEdGraphPinType MakeObjectPin(UClass* Class)
{
    FEdGraphPinType Type;
    Type.PinCategory = UEdGraphSchema_K2::PC_Object;
    Type.PinSubCategoryObject = Class;
    return Type;
}

FEdGraphPinType MakeBoolPin()
{
    FEdGraphPinType Type;
    Type.PinCategory = UEdGraphSchema_K2::PC_Boolean;
    return Type;
}

FEdGraphPinType MakeNamePin()
{
    FEdGraphPinType Type;
    Type.PinCategory = UEdGraphSchema_K2::PC_Name;
    return Type;
}

FEdGraphPinType MakeFloatPin()
{
    FEdGraphPinType Type;
    Type.PinCategory = UEdGraphSchema_K2::PC_Real;
    Type.PinSubCategory = UEdGraphSchema_K2::PC_Float;
    return Type;
}

bool SamePinType(const FEdGraphPinType& A, const FEdGraphPinType& B)
{
    return A.PinCategory == B.PinCategory &&
        A.PinSubCategory == B.PinSubCategory &&
        A.PinSubCategoryObject == B.PinSubCategoryObject &&
        A.ContainerType == B.ContainerType;
}

FBPVariableDescription* FindVariable(UBlueprint* Blueprint, const FName VarName)
{
    if (!Blueprint)
    {
        return nullptr;
    }

    for (FBPVariableDescription& Variable : Blueprint->NewVariables)
    {
        if (Variable.VarName == VarName)
        {
            return &Variable;
        }
    }

    return nullptr;
}

bool EnsureVariable(
    UBlueprint* Blueprint,
    const FName VarName,
    const FEdGraphPinType& VarType,
    const FString& Category,
    bool bInstanceEditable,
    const FString& DefaultValue,
    FBuildStats& Stats)
{
    if (!Blueprint)
    {
        return false;
    }

    FBPVariableDescription* Existing = FindVariable(Blueprint, VarName);
    const bool bHadExistingVariable = Existing != nullptr;
    if (!Existing)
    {
        if (!FBlueprintEditorUtils::AddMemberVariable(Blueprint, VarName, VarType, DefaultValue))
        {
            Stats.Warnings.Add(FString::Printf(TEXT("Failed to add variable %s"), *VarName.ToString()));
            return false;
        }
        Existing = FindVariable(Blueprint, VarName);
        Stats.VariablesAdded++;
    }
    else
    {
        if (!SamePinType(Existing->VarType, VarType))
        {
            Existing->VarType = VarType;
        }
        Stats.VariablesUpdated++;
    }

    if (Existing)
    {
        Existing->Category = FText::FromString(Category);
        if (!bHadExistingVariable || !DefaultValue.IsEmpty())
        {
            Existing->DefaultValue = DefaultValue;
        }
        Existing->PropertyFlags |= CPF_BlueprintVisible;
        Existing->PropertyFlags &= ~CPF_BlueprintReadOnly;
        if (bInstanceEditable)
        {
            Existing->PropertyFlags |= CPF_Edit;
            Existing->PropertyFlags &= ~CPF_DisableEditOnInstance;
        }
        else
        {
            Existing->PropertyFlags &= ~CPF_Edit;
            Existing->PropertyFlags |= CPF_DisableEditOnInstance;
        }
    }

    return true;
}

UEdGraph* FindFunctionGraph(UBlueprint* Blueprint, const FName FunctionName)
{
    if (!Blueprint)
    {
        return nullptr;
    }

    for (UEdGraph* Graph : Blueprint->FunctionGraphs)
    {
        if (Graph && Graph->GetFName() == FunctionName)
        {
            return Graph;
        }
    }

    return nullptr;
}

UEdGraph* RecreateFunctionGraph(UBlueprint* Blueprint, const FName FunctionName)
{
    if (!Blueprint)
    {
        return nullptr;
    }

    if (UEdGraph* Existing = FindFunctionGraph(Blueprint, FunctionName))
    {
        FBlueprintEditorUtils::RemoveGraph(Blueprint, Existing);
    }

    UEdGraph* NewGraph = FBlueprintEditorUtils::CreateNewGraph(
        Blueprint,
        FunctionName,
        UEdGraph::StaticClass(),
        UEdGraphSchema_K2::StaticClass());

    if (!NewGraph)
    {
        return nullptr;
    }

    FBlueprintEditorUtils::AddFunctionGraph<UClass>(Blueprint, NewGraph, true, nullptr);
    return NewGraph;
}

UK2Node_FunctionEntry* FindFunctionEntry(UEdGraph* Graph)
{
    if (!Graph)
    {
        return nullptr;
    }

    for (UEdGraphNode* Node : Graph->Nodes)
    {
        if (UK2Node_FunctionEntry* Entry = Cast<UK2Node_FunctionEntry>(Node))
        {
            return Entry;
        }
    }

    return nullptr;
}

UEdGraphPin* FindPin(UEdGraphNode* Node, const FString& PinName, EEdGraphPinDirection Direction = EGPD_MAX)
{
    if (!Node)
    {
        return nullptr;
    }

    for (UEdGraphPin* Pin : Node->Pins)
    {
        if (!Pin)
        {
            continue;
        }

        if (Pin->PinName.ToString() == PinName && (Direction == EGPD_MAX || Pin->Direction == Direction))
        {
            return Pin;
        }
    }

    return nullptr;
}

bool Link(UEdGraph* Graph, UEdGraphPin* Source, UEdGraphPin* Target, FBuildStats& Stats)
{
    if (!Graph || !Source || !Target)
    {
        Stats.Warnings.Add(TEXT("Skipped link because a pin was missing"));
        return false;
    }

    const UEdGraphSchema* Schema = Graph->GetSchema();
    if (Schema && Schema->TryCreateConnection(Source, Target))
    {
        return true;
    }

    Source->MakeLinkTo(Target);
    return true;
}

template <typename TNode>
TNode* PrepareNode(UEdGraph* Graph, TNode* Node, int32 PosX, int32 PosY, FBuildStats& Stats)
{
    if (!Graph || !Node)
    {
        return nullptr;
    }

    Node->NodePosX = PosX;
    Node->NodePosY = PosY;
    Node->NodeComment = GeneratedComment;
    Node->CreateNewGuid();
    Graph->AddNode(Node, true, false);
    Node->PostPlacedNewNode();
    Node->AllocateDefaultPins();
    Stats.NodesCreated++;
    return Node;
}

UK2Node_CallFunction* AddFunctionCall(UEdGraph* Graph, UFunction* Function, int32 PosX, int32 PosY, FBuildStats& Stats)
{
    if (!Graph || !Function)
    {
        return nullptr;
    }

    UK2Node_CallFunction* Node = NewObject<UK2Node_CallFunction>(Graph);
    Node->SetFromFunction(Function);
    return PrepareNode(Graph, Node, PosX, PosY, Stats);
}

UK2Node_CallFunction* AddSelfFunctionCall(UEdGraph* Graph, const FName FunctionName, int32 PosX, int32 PosY, FBuildStats& Stats)
{
    if (!Graph)
    {
        return nullptr;
    }

    UK2Node_CallFunction* Node = NewObject<UK2Node_CallFunction>(Graph);
    Node->FunctionReference.SetSelfMember(FunctionName);
    return PrepareNode(Graph, Node, PosX, PosY, Stats);
}

UK2Node_VariableGet* AddVariableGet(UEdGraph* Graph, const FName VarName, int32 PosX, int32 PosY, FBuildStats& Stats)
{
    UK2Node_VariableGet* Node = NewObject<UK2Node_VariableGet>(Graph);
    Node->VariableReference.SetSelfMember(VarName);
    return PrepareNode(Graph, Node, PosX, PosY, Stats);
}

UK2Node_VariableSet* AddVariableSet(UEdGraph* Graph, const FName VarName, int32 PosX, int32 PosY, FBuildStats& Stats)
{
    UK2Node_VariableSet* Node = NewObject<UK2Node_VariableSet>(Graph);
    Node->VariableReference.SetSelfMember(VarName);
    return PrepareNode(Graph, Node, PosX, PosY, Stats);
}

UK2Node_IfThenElse* AddBranch(UEdGraph* Graph, int32 PosX, int32 PosY, FBuildStats& Stats)
{
    UK2Node_IfThenElse* Node = NewObject<UK2Node_IfThenElse>(Graph);
    return PrepareNode(Graph, Node, PosX, PosY, Stats);
}

UK2Node_DynamicCast* AddDynamicCast(UEdGraph* Graph, UClass* TargetClass, int32 PosX, int32 PosY, FBuildStats& Stats)
{
    UK2Node_DynamicCast* Node = NewObject<UK2Node_DynamicCast>(Graph);
    Node->TargetType = TargetClass;
    Node->SetPurity(false);
    return PrepareNode(Graph, Node, PosX, PosY, Stats);
}

UK2Node_Event* FindOrCreateActorEvent(UBlueprint* Blueprint, UEdGraph* Graph, const FName EventName, int32 PosX, int32 PosY)
{
    if (!Blueprint || !Graph)
    {
        return nullptr;
    }

    for (UEdGraphNode* Node : Graph->Nodes)
    {
        if (UK2Node_Event* EventNode = Cast<UK2Node_Event>(Node))
        {
            if (EventNode->EventReference.GetMemberName() == EventName)
            {
                return EventNode;
            }
        }
    }

    UK2Node_Event* EventNode = NewObject<UK2Node_Event>(Graph);
    EventNode->EventReference.SetExternalMember(EventName, AActor::StaticClass());
    EventNode->bOverrideFunction = true;
    EventNode->NodePosX = PosX;
    EventNode->NodePosY = PosY;
    EventNode->CreateNewGuid();
    Graph->AddNode(EventNode, true, false);
    EventNode->PostPlacedNewNode();
    EventNode->AllocateDefaultPins();
    return EventNode;
}

void RemoveGeneratedNodes(UEdGraph* Graph, FBuildStats& Stats)
{
    if (!Graph)
    {
        return;
    }

    TArray<UEdGraphNode*> ToRemove;
    for (UEdGraphNode* Node : Graph->Nodes)
    {
        if (Node && Node->NodeComment == GeneratedComment)
        {
            ToRemove.Add(Node);
        }
    }

    for (UEdGraphNode* Node : ToRemove)
    {
        Node->BreakAllNodeLinks();
        Graph->RemoveNode(Node);
        Stats.NodesRemoved++;
    }
}

bool SetPinDefault(UEdGraphPin* Pin, const FString& Value)
{
    if (!Pin)
    {
        return false;
    }

    Pin->DefaultValue = Value;
    return true;
}

bool SetPinDefaultObject(UEdGraphPin* Pin, UObject* Object)
{
    if (!Pin)
    {
        return false;
    }

    Pin->DefaultObject = Object;
    Pin->DefaultValue = Object ? Object->GetPathName() : FString();
    return true;
}

bool SetPinDefaultClass(UEdGraphPin* Pin, UClass* Class)
{
    if (!Pin)
    {
        return false;
    }

    Pin->DefaultObject = Class;
    Pin->DefaultValue.Reset();
    Pin->AutogeneratedDefaultValue.Reset();
    return true;
}

void SetObjectPropertyValue(UObject* Object, const FName PropertyName, UObject* Value, FBuildStats& Stats)
{
    if (!Object)
    {
        return;
    }

    FObjectPropertyBase* Property = FindFProperty<FObjectPropertyBase>(Object->GetClass(), PropertyName);
    if (!Property)
    {
        Stats.Warnings.Add(FString::Printf(TEXT("Object property not found: %s"), *PropertyName.ToString()));
        return;
    }

    Property->SetObjectPropertyValue_InContainer(Object, Value);
}

void SetNamePropertyValue(UObject* Object, const FName PropertyName, const FName Value, FBuildStats& Stats)
{
    if (!Object)
    {
        return;
    }

    FNameProperty* Property = FindFProperty<FNameProperty>(Object->GetClass(), PropertyName);
    if (!Property)
    {
        Stats.Warnings.Add(FString::Printf(TEXT("Name property not found: %s"), *PropertyName.ToString()));
        return;
    }

    Property->SetPropertyValue_InContainer(Object, Value);
}

void SetFloatPropertyValue(UObject* Object, const FName PropertyName, double Value, FBuildStats& Stats)
{
    if (!Object)
    {
        return;
    }

    FNumericProperty* Property = FindFProperty<FNumericProperty>(Object->GetClass(), PropertyName);
    if (!Property || !Property->IsFloatingPoint())
    {
        Stats.Warnings.Add(FString::Printf(TEXT("Float property not found: %s"), *PropertyName.ToString()));
        return;
    }

    Property->SetFloatingPointPropertyValue(Property->ContainerPtrToValuePtr<void>(Object), Value);
}

void SetBoolPropertyValue(UObject* Object, const FName PropertyName, bool Value, FBuildStats& Stats)
{
    if (!Object)
    {
        return;
    }

    FBoolProperty* Property = FindFProperty<FBoolProperty>(Object->GetClass(), PropertyName);
    if (!Property)
    {
        Stats.Warnings.Add(FString::Printf(TEXT("Bool property not found: %s"), *PropertyName.ToString()));
        return;
    }

    Property->SetPropertyValue_InContainer(Object, Value);
}

bool ConnectExec(UEdGraph* Graph, UEdGraphNode* Source, const FString& SourcePin, UEdGraphNode* Target, FBuildStats& Stats)
{
    return Link(Graph, FindPin(Source, SourcePin, EGPD_Output), FindPin(Target, TEXT("execute"), EGPD_Input), Stats);
}

bool BuildFootFunction(
    UBlueprint* Blueprint,
    const FName FunctionName,
    const FName FootNameVariable,
    const FName GroundedVariable,
    FBuildStats& Stats)
{
    UEdGraph* Graph = RecreateFunctionGraph(Blueprint, FunctionName);
    if (!Graph)
    {
        Stats.Warnings.Add(FString::Printf(TEXT("Failed to create function graph %s"), *FunctionName.ToString()));
        return false;
    }

    UK2Node_FunctionEntry* Entry = FindFunctionEntry(Graph);
    if (!Entry)
    {
        Stats.Warnings.Add(FString::Printf(TEXT("Function %s has no entry node"), *FunctionName.ToString()));
        return false;
    }

    Entry->NodePosX = 0;
    Entry->NodePosY = 0;

    UK2Node_VariableGet* MeshGet = AddVariableGet(Graph, TEXT("ActiveFootprintMesh"), 0, 180, Stats);
    UK2Node_VariableGet* FootNameGet = AddVariableGet(Graph, FootNameVariable, 0, 340, Stats);
    UK2Node_CallFunction* SocketLoc = AddFunctionCall(Graph, USceneComponent::StaticClass()->FindFunctionByName(TEXT("GetSocketLocation")), 260, 240, Stats);

    UK2Node_CallFunction* StartOffset = AddFunctionCall(Graph, UKismetMathLibrary::StaticClass()->FindFunctionByName(TEXT("MakeVector")), 260, 20, Stats);
    SetPinDefault(FindPin(StartOffset, TEXT("X"), EGPD_Input), TEXT("0.0"));
    SetPinDefault(FindPin(StartOffset, TEXT("Y"), EGPD_Input), TEXT("0.0"));
    SetPinDefault(FindPin(StartOffset, TEXT("Z"), EGPD_Input), TEXT("12.0"));

    UK2Node_CallFunction* EndOffset = AddFunctionCall(Graph, UKismetMathLibrary::StaticClass()->FindFunctionByName(TEXT("MakeVector")), 260, 460, Stats);
    SetPinDefault(FindPin(EndOffset, TEXT("X"), EGPD_Input), TEXT("0.0"));
    SetPinDefault(FindPin(EndOffset, TEXT("Y"), EGPD_Input), TEXT("0.0"));
    SetPinDefault(FindPin(EndOffset, TEXT("Z"), EGPD_Input), TEXT("-35.0"));

    UK2Node_CallFunction* MakeStart = AddFunctionCall(Graph, UKismetMathLibrary::StaticClass()->FindFunctionByName(TEXT("Add_VectorVector")), 520, 80, Stats);
    UK2Node_CallFunction* MakeEnd = AddFunctionCall(Graph, UKismetMathLibrary::StaticClass()->FindFunctionByName(TEXT("Add_VectorVector")), 520, 420, Stats);
    UK2Node_VariableGet* RadiusGet = AddVariableGet(Graph, TEXT("TraceRadius"), 720, 560, Stats);
    UK2Node_CallFunction* Trace = AddFunctionCall(Graph, UKismetSystemLibrary::StaticClass()->FindFunctionByName(TEXT("SphereTraceSingle")), 780, 180, Stats);
    SetPinDefault(FindPin(Trace, TEXT("TraceChannel"), EGPD_Input), TEXT("TraceTypeQuery1"));
    SetPinDefault(FindPin(Trace, TEXT("bTraceComplex"), EGPD_Input), TEXT("false"));
    SetPinDefault(FindPin(Trace, TEXT("DrawDebugType"), EGPD_Input), TEXT("None"));
    SetPinDefault(FindPin(Trace, TEXT("bIgnoreSelf"), EGPD_Input), TEXT("true"));

    UK2Node_IfThenElse* TraceBranch = AddBranch(Graph, 1100, 180, Stats);
    UK2Node_VariableGet* GroundedGet = AddVariableGet(Graph, GroundedVariable, 1100, 390, Stats);
    UK2Node_CallFunction* NotGrounded = AddFunctionCall(Graph, UKismetMathLibrary::StaticClass()->FindFunctionByName(TEXT("Not_PreBool")), 1320, 380, Stats);
    UK2Node_IfThenElse* EdgeBranch = AddBranch(Graph, 1540, 200, Stats);
    UK2Node_CallFunction* BreakHit = AddFunctionCall(Graph, UGameplayStatics::StaticClass()->FindFunctionByName(TEXT("BreakHitResult")), 1320, 20, Stats);
    UK2Node_VariableGet* SystemGet = AddVariableGet(Graph, TEXT("FootprintSystem"), 1540, 20, Stats);
    UK2Node_CallFunction* Spawn = AddFunctionCall(Graph, UNiagaraFunctionLibrary::StaticClass()->FindFunctionByName(TEXT("SpawnSystemAtLocation")), 1780, 120, Stats);
    UK2Node_VariableSet* SetGroundedTrue = AddVariableSet(Graph, GroundedVariable, 2040, 160, Stats);
    UK2Node_VariableSet* SetGroundedFalse = AddVariableSet(Graph, GroundedVariable, 1320, 640, Stats);
    SetPinDefault(FindPin(SetGroundedTrue, GroundedVariable.ToString(), EGPD_Input), TEXT("true"));
    SetPinDefault(FindPin(SetGroundedFalse, GroundedVariable.ToString(), EGPD_Input), TEXT("false"));

    Link(Graph, FindPin(MeshGet, TEXT("ActiveFootprintMesh"), EGPD_Output), FindPin(SocketLoc, TEXT("self"), EGPD_Input), Stats);
    Link(Graph, FindPin(FootNameGet, FootNameVariable.ToString(), EGPD_Output), FindPin(SocketLoc, TEXT("InSocketName"), EGPD_Input), Stats);
    Link(Graph, FindPin(SocketLoc, TEXT("ReturnValue"), EGPD_Output), FindPin(MakeStart, TEXT("A"), EGPD_Input), Stats);
    Link(Graph, FindPin(StartOffset, TEXT("ReturnValue"), EGPD_Output), FindPin(MakeStart, TEXT("B"), EGPD_Input), Stats);
    Link(Graph, FindPin(SocketLoc, TEXT("ReturnValue"), EGPD_Output), FindPin(MakeEnd, TEXT("A"), EGPD_Input), Stats);
    Link(Graph, FindPin(EndOffset, TEXT("ReturnValue"), EGPD_Output), FindPin(MakeEnd, TEXT("B"), EGPD_Input), Stats);
    Link(Graph, FindPin(MakeStart, TEXT("ReturnValue"), EGPD_Output), FindPin(Trace, TEXT("Start"), EGPD_Input), Stats);
    Link(Graph, FindPin(MakeEnd, TEXT("ReturnValue"), EGPD_Output), FindPin(Trace, TEXT("End"), EGPD_Input), Stats);
    Link(Graph, FindPin(RadiusGet, TEXT("TraceRadius"), EGPD_Output), FindPin(Trace, TEXT("Radius"), EGPD_Input), Stats);

    Link(Graph, FindPin(Entry, TEXT("then"), EGPD_Output), FindPin(Trace, TEXT("execute"), EGPD_Input), Stats);
    Link(Graph, FindPin(Trace, TEXT("then"), EGPD_Output), FindPin(TraceBranch, TEXT("execute"), EGPD_Input), Stats);
    Link(Graph, FindPin(Trace, TEXT("ReturnValue"), EGPD_Output), FindPin(TraceBranch, TEXT("Condition"), EGPD_Input), Stats);
    Link(Graph, FindPin(Trace, TEXT("OutHit"), EGPD_Output), FindPin(BreakHit, TEXT("Hit"), EGPD_Input), Stats);
    Link(Graph, FindPin(GroundedGet, GroundedVariable.ToString(), EGPD_Output), FindPin(NotGrounded, TEXT("A"), EGPD_Input), Stats);
    Link(Graph, FindPin(NotGrounded, TEXT("ReturnValue"), EGPD_Output), FindPin(EdgeBranch, TEXT("Condition"), EGPD_Input), Stats);
    Link(Graph, FindPin(TraceBranch, TEXT("then"), EGPD_Output), FindPin(EdgeBranch, TEXT("execute"), EGPD_Input), Stats);
    Link(Graph, FindPin(TraceBranch, TEXT("else"), EGPD_Output), FindPin(SetGroundedFalse, TEXT("execute"), EGPD_Input), Stats);
    Link(Graph, FindPin(EdgeBranch, TEXT("then"), EGPD_Output), FindPin(Spawn, TEXT("execute"), EGPD_Input), Stats);
    Link(Graph, FindPin(SystemGet, TEXT("FootprintSystem"), EGPD_Output), FindPin(Spawn, TEXT("SystemTemplate"), EGPD_Input), Stats);
    Link(Graph, FindPin(BreakHit, TEXT("Location"), EGPD_Output), FindPin(Spawn, TEXT("Location"), EGPD_Input), Stats);
    Link(Graph, FindPin(Spawn, TEXT("then"), EGPD_Output), FindPin(SetGroundedTrue, TEXT("execute"), EGPD_Input), Stats);

    Graph->NotifyGraphChanged();
    return true;
}

bool BuildBeginOverlap(UEdGraph* Graph, UK2Node_Event* Event, FBuildStats& Stats)
{
    if (!Graph || !Event)
    {
        return false;
    }

    UK2Node_VariableSet* SetActor = AddVariableSet(Graph, TEXT("ActiveFootprintActor"), 320, 210, Stats);
    UK2Node_CallFunction* GetComponent = AddFunctionCall(Graph, AActor::StaticClass()->FindFunctionByName(TEXT("GetComponentByClass")), 600, 210, Stats);
    SetPinDefaultClass(FindPin(GetComponent, TEXT("ComponentClass"), EGPD_Input), USkeletalMeshComponent::StaticClass());
    GetComponent->ReconstructNode();

    UK2Node_DynamicCast* CastMesh = AddDynamicCast(Graph, USkeletalMeshComponent::StaticClass(), 880, 210, Stats);
    UK2Node_VariableSet* SetMesh = AddVariableSet(Graph, TEXT("ActiveFootprintMesh"), 1160, 210, Stats);
    UK2Node_VariableSet* SetLeft = AddVariableSet(Graph, TEXT("bLeftFootGrounded"), 1440, 180, Stats);
    UK2Node_VariableSet* SetRight = AddVariableSet(Graph, TEXT("bRightFootGrounded"), 1720, 180, Stats);
    SetPinDefault(FindPin(SetLeft, TEXT("bLeftFootGrounded"), EGPD_Input), TEXT("false"));
    SetPinDefault(FindPin(SetRight, TEXT("bRightFootGrounded"), EGPD_Input), TEXT("false"));

    Link(Graph, FindPin(Event, TEXT("then"), EGPD_Output), FindPin(SetActor, TEXT("execute"), EGPD_Input), Stats);
    Link(Graph, FindPin(Event, TEXT("OtherActor"), EGPD_Output), FindPin(SetActor, TEXT("ActiveFootprintActor"), EGPD_Input), Stats);
    Link(Graph, FindPin(Event, TEXT("OtherActor"), EGPD_Output), FindPin(GetComponent, TEXT("self"), EGPD_Input), Stats);
    Link(Graph, FindPin(SetActor, TEXT("then"), EGPD_Output), CastMesh->GetExecPin(), Stats);
    Link(Graph, FindPin(GetComponent, TEXT("ReturnValue"), EGPD_Output), CastMesh->GetCastSourcePin(), Stats);
    Link(Graph, CastMesh->GetValidCastPin(), FindPin(SetMesh, TEXT("execute"), EGPD_Input), Stats);
    Link(Graph, CastMesh->GetCastResultPin(), FindPin(SetMesh, TEXT("ActiveFootprintMesh"), EGPD_Input), Stats);
    Link(Graph, FindPin(SetMesh, TEXT("then"), EGPD_Output), FindPin(SetLeft, TEXT("execute"), EGPD_Input), Stats);
    Link(Graph, FindPin(SetLeft, TEXT("then"), EGPD_Output), FindPin(SetRight, TEXT("execute"), EGPD_Input), Stats);
    return true;
}

bool BuildEndOverlap(UEdGraph* Graph, UK2Node_Event* Event, FBuildStats& Stats)
{
    if (!Graph || !Event)
    {
        return false;
    }

    UK2Node_VariableGet* ActiveActor = AddVariableGet(Graph, TEXT("ActiveFootprintActor"), 280, 560, Stats);
    UK2Node_CallFunction* Equal = AddFunctionCall(Graph, UKismetMathLibrary::StaticClass()->FindFunctionByName(TEXT("EqualEqual_ObjectObject")), 540, 540, Stats);
    UK2Node_IfThenElse* Branch = AddBranch(Graph, 780, 520, Stats);
    UK2Node_VariableSet* ClearActor = AddVariableSet(Graph, TEXT("ActiveFootprintActor"), 1040, 520, Stats);
    UK2Node_VariableSet* ClearMesh = AddVariableSet(Graph, TEXT("ActiveFootprintMesh"), 1320, 520, Stats);
    UK2Node_VariableSet* SetLeft = AddVariableSet(Graph, TEXT("bLeftFootGrounded"), 1600, 500, Stats);
    UK2Node_VariableSet* SetRight = AddVariableSet(Graph, TEXT("bRightFootGrounded"), 1880, 500, Stats);
    SetPinDefault(FindPin(SetLeft, TEXT("bLeftFootGrounded"), EGPD_Input), TEXT("false"));
    SetPinDefault(FindPin(SetRight, TEXT("bRightFootGrounded"), EGPD_Input), TEXT("false"));

    Link(Graph, FindPin(Event, TEXT("OtherActor"), EGPD_Output), FindPin(Equal, TEXT("A"), EGPD_Input), Stats);
    Link(Graph, FindPin(ActiveActor, TEXT("ActiveFootprintActor"), EGPD_Output), FindPin(Equal, TEXT("B"), EGPD_Input), Stats);
    Link(Graph, FindPin(Event, TEXT("then"), EGPD_Output), FindPin(Branch, TEXT("execute"), EGPD_Input), Stats);
    Link(Graph, FindPin(Equal, TEXT("ReturnValue"), EGPD_Output), FindPin(Branch, TEXT("Condition"), EGPD_Input), Stats);
    Link(Graph, FindPin(Branch, TEXT("then"), EGPD_Output), FindPin(ClearActor, TEXT("execute"), EGPD_Input), Stats);
    Link(Graph, FindPin(ClearActor, TEXT("then"), EGPD_Output), FindPin(ClearMesh, TEXT("execute"), EGPD_Input), Stats);
    Link(Graph, FindPin(ClearMesh, TEXT("then"), EGPD_Output), FindPin(SetLeft, TEXT("execute"), EGPD_Input), Stats);
    Link(Graph, FindPin(SetLeft, TEXT("then"), EGPD_Output), FindPin(SetRight, TEXT("execute"), EGPD_Input), Stats);
    return true;
}

bool BuildTick(UEdGraph* Graph, UK2Node_Event* TickEvent, FBuildStats& Stats)
{
    if (!Graph || !TickEvent)
    {
        return false;
    }

    UK2Node_VariableGet* MeshGet = AddVariableGet(Graph, TEXT("ActiveFootprintMesh"), 280, 880, Stats);
    UK2Node_CallFunction* IsValid = AddFunctionCall(Graph, UKismetSystemLibrary::StaticClass()->FindFunctionByName(TEXT("IsValid")), 540, 860, Stats);
    UK2Node_IfThenElse* Branch = AddBranch(Graph, 780, 840, Stats);
    UK2Node_CallFunction* CheckLeft = AddSelfFunctionCall(Graph, FnLeft, 1040, 830, Stats);
    UK2Node_CallFunction* CheckRight = AddSelfFunctionCall(Graph, FnRight, 1320, 830, Stats);

    Link(Graph, FindPin(MeshGet, TEXT("ActiveFootprintMesh"), EGPD_Output), FindPin(IsValid, TEXT("Object"), EGPD_Input), Stats);
    Link(Graph, FindPin(TickEvent, TEXT("then"), EGPD_Output), FindPin(Branch, TEXT("execute"), EGPD_Input), Stats);
    Link(Graph, FindPin(IsValid, TEXT("ReturnValue"), EGPD_Output), FindPin(Branch, TEXT("Condition"), EGPD_Input), Stats);
    Link(Graph, FindPin(Branch, TEXT("then"), EGPD_Output), FindPin(CheckLeft, TEXT("execute"), EGPD_Input), Stats);
    Link(Graph, FindPin(CheckLeft, TEXT("then"), EGPD_Output), FindPin(CheckRight, TEXT("execute"), EGPD_Input), Stats);
    return true;
}

void SetDefaults(UBlueprint* Blueprint, const TSharedPtr<FJsonObject>& Params, FBuildStats& Stats)
{
    if (!Blueprint || !Blueprint->GeneratedClass)
    {
        return;
    }

    UObject* CDO = Blueprint->GeneratedClass->GetDefaultObject();
    if (!CDO)
    {
        return;
    }

    FString NiagaraPath = TEXT("/Game/Effects_HD_fixed/Characters/Common/NS_Footprint.NS_Footprint");
    Params->TryGetStringField(TEXT("niagara_system_path"), NiagaraPath);

    FString LeftFootName = TEXT("foot_l");
    FString RightFootName = TEXT("foot_r");
    Params->TryGetStringField(TEXT("left_foot_name"), LeftFootName);
    Params->TryGetStringField(TEXT("right_foot_name"), RightFootName);

    double TraceRadius = 5.0;
    Params->TryGetNumberField(TEXT("trace_radius"), TraceRadius);

    if (UNiagaraSystem* Niagara = Cast<UNiagaraSystem>(UEditorAssetLibrary::LoadAsset(NiagaraPath)))
    {
        SetObjectPropertyValue(CDO, TEXT("FootprintSystem"), Niagara, Stats);
    }
    else
    {
        Stats.Warnings.Add(FString::Printf(TEXT("Failed to load Niagara system: %s"), *NiagaraPath));
    }

    SetNamePropertyValue(CDO, TEXT("LeftFootName"), FName(*LeftFootName), Stats);
    SetNamePropertyValue(CDO, TEXT("RightFootName"), FName(*RightFootName), Stats);
    SetFloatPropertyValue(CDO, TEXT("TraceRadius"), TraceRadius, Stats);
    SetBoolPropertyValue(CDO, TEXT("bLeftFootGrounded"), false, Stats);
    SetBoolPropertyValue(CDO, TEXT("bRightFootGrounded"), false, Stats);
}
}

TSharedPtr<FJsonObject> FExtractionFootprintGraphBuilder::SetupGraph(const TSharedPtr<FJsonObject>& Params)
{
    if (!Params.IsValid())
    {
        return FEpicUnrealMCPCommonUtils::CreateErrorResponse(TEXT("Invalid parameters"));
    }

    FString BlueprintName;
    if (!Params->TryGetStringField(TEXT("blueprint_name"), BlueprintName))
    {
        return FEpicUnrealMCPCommonUtils::CreateErrorResponse(TEXT("Missing 'blueprint_name' parameter"));
    }

    UBlueprint* Blueprint = FEpicUnrealMCPCommonUtils::FindBlueprint(BlueprintName);
    if (!Blueprint)
    {
        return FEpicUnrealMCPCommonUtils::CreateErrorResponse(FString::Printf(TEXT("Blueprint not found: %s"), *BlueprintName));
    }

    if (Blueprint->UbergraphPages.Num() == 0 || !Blueprint->UbergraphPages[0])
    {
        return FEpicUnrealMCPCommonUtils::CreateErrorResponse(TEXT("Blueprint has no EventGraph"));
    }

    FBuildStats Stats;
    UEdGraph* EventGraph = Blueprint->UbergraphPages[0];

    UE_LOG(LogTemp, Display, TEXT("FExtractionFootprintGraphBuilder::SetupGraph: ensuring variables"));

    EnsureVariable(Blueprint, TEXT("FootprintSystem"), MakeObjectPin(UNiagaraSystem::StaticClass()), TEXT("Footprint Detection"), true, TEXT(""), Stats);
    EnsureVariable(Blueprint, TEXT("LeftFootName"), MakeNamePin(), TEXT("Footprint Detection"), true, TEXT("foot_l"), Stats);
    EnsureVariable(Blueprint, TEXT("RightFootName"), MakeNamePin(), TEXT("Footprint Detection"), true, TEXT("foot_r"), Stats);
    EnsureVariable(Blueprint, TEXT("TraceRadius"), MakeFloatPin(), TEXT("Footprint Detection"), true, TEXT("5.0"), Stats);
    EnsureVariable(Blueprint, TEXT("ActiveFootprintActor"), MakeObjectPin(AActor::StaticClass()), TEXT("Footprint Runtime"), false, TEXT(""), Stats);
    EnsureVariable(Blueprint, TEXT("ActiveFootprintMesh"), MakeObjectPin(USkeletalMeshComponent::StaticClass()), TEXT("Footprint Runtime"), false, TEXT(""), Stats);
    EnsureVariable(Blueprint, TEXT("bLeftFootGrounded"), MakeBoolPin(), TEXT("Footprint Runtime"), false, TEXT("false"), Stats);
    EnsureVariable(Blueprint, TEXT("bRightFootGrounded"), MakeBoolPin(), TEXT("Footprint Runtime"), false, TEXT("false"), Stats);

    UE_LOG(LogTemp, Display, TEXT("FExtractionFootprintGraphBuilder::SetupGraph: removing generated event nodes"));
    RemoveGeneratedNodes(EventGraph, Stats);

    bool bSetDefaults = false;
    Params->TryGetBoolField(TEXT("set_defaults"), bSetDefaults);
    if (bSetDefaults)
    {
        UE_LOG(LogTemp, Display, TEXT("FExtractionFootprintGraphBuilder::SetupGraph: compiling variables"));
        FKismetEditorUtilities::CompileBlueprint(Blueprint);
    }

    if (bSetDefaults)
    {
        UE_LOG(LogTemp, Display, TEXT("FExtractionFootprintGraphBuilder::SetupGraph: setting defaults"));
        SetDefaults(Blueprint, Params, Stats);
    }
    else
    {
        UE_LOG(LogTemp, Display, TEXT("FExtractionFootprintGraphBuilder::SetupGraph: skipping defaults"));
    }

    UE_LOG(LogTemp, Display, TEXT("FExtractionFootprintGraphBuilder::SetupGraph: building foot functions"));
    if (!BuildFootFunction(Blueprint, FnLeft, TEXT("LeftFootName"), TEXT("bLeftFootGrounded"), Stats))
    {
        return FEpicUnrealMCPCommonUtils::CreateErrorResponse(TEXT("Failed to build MCP_CheckLeftFoot"));
    }
    if (!BuildFootFunction(Blueprint, FnRight, TEXT("RightFootName"), TEXT("bRightFootGrounded"), Stats))
    {
        return FEpicUnrealMCPCommonUtils::CreateErrorResponse(TEXT("Failed to build MCP_CheckRightFoot"));
    }

    UE_LOG(LogTemp, Display, TEXT("FExtractionFootprintGraphBuilder::SetupGraph: building event graph"));
    UK2Node_Event* BeginOverlap = FindOrCreateActorEvent(Blueprint, EventGraph, TEXT("ReceiveActorBeginOverlap"), 0, 210);
    UK2Node_Event* EndOverlap = FindOrCreateActorEvent(Blueprint, EventGraph, TEXT("ReceiveActorEndOverlap"), 0, 560);
    UK2Node_Event* Tick = FindOrCreateActorEvent(Blueprint, EventGraph, TEXT("ReceiveTick"), 0, 840);

    BuildBeginOverlap(EventGraph, BeginOverlap, Stats);
    BuildEndOverlap(EventGraph, EndOverlap, Stats);
    BuildTick(EventGraph, Tick, Stats);

    EventGraph->NotifyGraphChanged();
    FBlueprintEditorUtils::MarkBlueprintAsStructurallyModified(Blueprint);

    bool bCompile = true;
    Params->TryGetBoolField(TEXT("compile"), bCompile);
    if (bCompile)
    {
        UE_LOG(LogTemp, Display, TEXT("FExtractionFootprintGraphBuilder::SetupGraph: compiling generated graph"));
        FKismetEditorUtilities::CompileBlueprint(Blueprint);
    }
    else
    {
        UE_LOG(LogTemp, Display, TEXT("FExtractionFootprintGraphBuilder::SetupGraph: skipping generated graph compile"));
    }

    bool bSave = false;
    Params->TryGetBoolField(TEXT("save"), bSave);
    if (bSave)
    {
        UE_LOG(LogTemp, Display, TEXT("FExtractionFootprintGraphBuilder::SetupGraph: saving blueprint"));
        UEditorAssetLibrary::SaveLoadedAsset(Blueprint);
    }
    else
    {
        UE_LOG(LogTemp, Display, TEXT("FExtractionFootprintGraphBuilder::SetupGraph: skipping save"));
    }

    UE_LOG(LogTemp, Display, TEXT("FExtractionFootprintGraphBuilder::SetupGraph: completed"));

    TSharedPtr<FJsonObject> Result = MakeShared<FJsonObject>();
    Result->SetBoolField(TEXT("success"), true);
    Result->SetStringField(TEXT("blueprint_name"), BlueprintName);
    Result->SetNumberField(TEXT("nodes_created"), Stats.NodesCreated);
    Result->SetNumberField(TEXT("nodes_removed"), Stats.NodesRemoved);
    Result->SetNumberField(TEXT("variables_added"), Stats.VariablesAdded);
    Result->SetNumberField(TEXT("variables_updated"), Stats.VariablesUpdated);
    Result->SetBoolField(TEXT("defaults_set"), bSetDefaults);
    Result->SetBoolField(TEXT("compiled"), bCompile);
    Result->SetBoolField(TEXT("saved"), bSave);

    TArray<TSharedPtr<FJsonValue>> FunctionNames;
    FunctionNames.Add(MakeShared<FJsonValueString>(FnLeft.ToString()));
    FunctionNames.Add(MakeShared<FJsonValueString>(FnRight.ToString()));
    Result->SetArrayField(TEXT("generated_functions"), FunctionNames);

    TArray<TSharedPtr<FJsonValue>> Warnings;
    for (const FString& Warning : Stats.Warnings)
    {
        Warnings.Add(MakeShared<FJsonValueString>(Warning));
    }
    Result->SetArrayField(TEXT("warnings"), Warnings);

    return Result;
}
